### ISSUE TITLE
OpenResty doesn't install

### ISSUE THREAD

**Issue by LennyPenny** [erikcw/docker-lapis#1]
Logs say this when running the container

> Aborting: can not find an installation of OpenResty

**Comment by erikcw** [comment]
It's working fine for me.  Can you share the exact command you are using to run the container?  Also, which OS are you on?

**Comment by erikcw** [comment]
The container was build under the assumption that you would supply your own configuration (ie by creating your own Dockerfile `FROM erikcw/lapis:latest`).

I've added a demo lapis app so you can "test drive" the container.

Try this:

```
docker pull erikcw/lapis:latest
run -it --rm --name resty -p 8080:8080 erikcw/lapis:latest

# in another terminal
curl http://localhost:8080/
```
